apiVersion: v1
kind: Service
metadata:
  labels:
    app: srv-ml-stockprice
  name: srv-ml-stockprice
  namespace: stockprice
spec:
  ports:
  - nodePort: 32000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: srv-ml-stockprice
  type: NodePort
